model_list:
  - model_name: glm-free
    litellm_params:
      model: openai/z-ai/glm-5.2-free
      api_base: https://api.tokenrouter.com/v1
      api_key: os.environ/TOKENROUTER_API_KEY
      custom_llm_provider: openai
      drop_params: true

litellm_settings:
  set_verbose: true
  drop_params: true

general_settings:
  master_key: anything